In [2]:
# Dependencies
import os
import pandas as pd

## Extract

In [3]:
crime_csv = "../Resources/Neighbourhood_Crime_Rates.csv"
crime_df = pd.read_csv(crime_csv)
crime_df.head()

,_id,OBJECTID,Neighbourhood,Hood_ID,Population,Assault_2014,Assault_2015,Assault_2016,Assault_2017,Assault_2018,...,TheftOver_2016,TheftOver_2017,TheftOver_2018,TheftOver_2019,TheftOver_AVG,TheftOver_CHG,TheftOver_Rate_2019,Shape__Area,Shape__Length,geometry
0,1,16,South Parkdale,85,21849,202,226,231,229,220,...,9,10,9,22,10.0,1.44,100.7,2.286974e+06,10802.83216,"{u'type': u'Polygon', u'coordinates': (((-79.4..."
1,2,17,South Riverdale,70,27876,215,207,236,243,304,...,22,27,24,21,21.3,-0.13,75.3,1.096457e+07,43080.72470,"{u'type': u'Polygon', u'coordinates': (((-79.3..."
2,3,18,St.Andrew-Windfields,40,17812,53,41,48,45,55,...,8,7,6,6,8.5,0.00,33.7,7.299580e+06,13025.99746,"{u'type': u'Polygon', u'coordinates': (((-79.3..."
3,4,19,Taylor-Massey,61,15683,127,92,97,107,123,...,5,2,4,3,3.5,-0.25,19.1,1.062970e+06,5940.70005,"{u'type': u'Polygon', u'coordinates': (((-79.2..."
4,5,20,Humber Summit,21,12416,76,89,118,116,109,...,18,18,15,22,17.3,0.47,177.2,7.966905e+06,12608.57312,"{u'type': u'Polygon', u'coordinates': (((-79.5..."

## Transform

In [6]:
# Remove unwanted columns
crime_df = crime_df.loc[:,["Neighbourhood", "Hood_ID", "Assault_Rate_2019", "AutoTheft_Rate_2019", "BreakandEnter_Rate_2019", "Homicide_Rate_2019", "Robbery_Rate_2019", "TheftOver_Rate_2019"]]

# Calculate total averate crime rates and create a new column for the values
# Crime Rates: Rate of crimes for 2019 per 100,000 population 
crime_df["total_average_crime_rate"] = round((crime_df["Assault_Rate_2019"] + crime_df["AutoTheft_Rate_2019"] + crime_df["BreakandEnter_Rate_2019"] +
                                       crime_df["Homicide_Rate_2019"] + crime_df["Robbery_Rate_2019"] + crime_df["TheftOver_Rate_2019"]) / 6, 2)

# Remove unwanted columns
crime = crime_df.loc[:,["Neighbourhood", "Hood_ID", "total_average_crime_rate"]]


# Rename the columns names
crime = crime.rename(columns={"Hood_ID" : "neighbourhood_id",
                              "Neighbourhood" : "neighbourhood_name"
                             })

# Set index as neighbourhood_id
crime = crime.set_index('neighbourhood_id')
crime_rate = crime.sort_index()

## Final Transformed Crime Table

In [7]:
crime_rate

                                 neighbourhood_name  total_average_crime_rate
neighbourhood_id
1                            West Humber-Clairville                    507.32
2                 Mount Olive-Silverstone-Jamestown                    232.13
3                      Thistletown-Beaumond Heights                    236.50
4                                   Rexdale-Kipling                    245.35
5                                  Elms-Old Rexdale                    216.80
...                                             ...                       ...
136                                       West Hill                    383.95
137                                          Woburn                    206.32
138                                   Eglinton East                    231.97
139                             Scarborough Village                    262.10
140                                       Guildwood                     84.03

[140 rows x 2 columns]

In [8]:
crime_rate.to_csv('../clean_data/crime.csv')